alter table sustc.public.company add unique (name);
alter table sustc.public.city add unique (name);
alter table sustc.public.container add unique (code);
alter table sustc.public.ship add unique (name);
alter table sustc.public.ship add foreign key (company_id) references company(id);
alter table sustc.public.courier add unique(name,phone_number);
alter table sustc.public.courier add foreign key (company_id) references company(id);
alter table sustc.public.courier add foreign key (city_id) references city(id);
alter table sustc.public.record add unique (item_name);
alter table sustc.public.record add foreign key (container_id) references container(id);
alter table sustc.public.record add foreign key (company_id) references company(id);
alter table sustc.public.record add foreign key (ship_id) references ship(id);
alter table sustc.public.handle add unique (type,record_id,courier_id);
alter table sustc.public.handle add foreign key (record_id) references record(id);
alter table sustc.public.handle add foreign key (courier_id) references courier(id);
alter table sustc.public.transit add unique (type,record_id,city_id);
alter table sustc.public.transit add foreign key (record_id) references record(id);
alter table sustc.public.transit add foreign key (city_id) references city(id);
create index handle_courier_id on sustc.public.handle(courier_id);
create index handle_record_id  on sustc.public.handle(record_id);
create index transit_record_id on sustc.public.transit(record_id);